### ISSUE TITLE
Need .env file and running configuration

### ISSUE THREAD

**Issue by sp5594** [AntennaeVY/sockets-ticket-queues#2]
Could you please provide the .env file and running configuration for the server? Also db setup?

**Comment by AntennaeVY** [comment]
Sure man, the project is a bit old but I'll do my best for you

**Comment by AntennaeVY** [comment]
You need to place a `.env` file inside the `/src` directory containing the following
```env
# A valid mongodb URI pointing to an existing instance of MongoDB running in your computer, cloud or some docker container, for example: 
DATABASE_URI=mongodb://localhost:27017
# Any available port you want to serve the app in
PORT=5005
```

As for the DB setup you only need the MongoDB instance running, the server will create the corresponding structure
To run de app first execute `npm install` in the root folder and then either `npm run start` or `npm run start-dev` to start the project.

Let me know if you need further assistance

**Comment by sp5594** [comment]
I'm getting this error when I run the app, see below. When I go to generate a ticket, it says ticket undefined.

```
App listening on port  5005
DB Error:  MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at Connection.openUri (/Users/Shail/ticket-queues/node_modules/mongoose/lib/connection.js:846:32)
    at /Users/Shail/ticket-queues/node_modules/mongoose/lib/index.js:351:10
    at /Users/Shail/ticket-queues/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/Shail/ticket-queues/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/Users/Shail/ticket-queues/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/Users/Shail/ticket-queues/node_modules/mongoose/lib/index.js:350:20)
    at /Users/Shail/ticket-queues/src/database/database.js:5:6
    at Object.<anonymous> (/Users/Shail/ticket-queues/src/database/database.js:16:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/Shail/ticket-queues/src/server.js:17:1) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
Client connected from  ::1
MongooseError: Operation `ticketcontrols.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/Shail/ticket-queues/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:197:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
MongooseError: Operation `ticketcontrols.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/Shail/ticket-queues/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:197:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
TypeError: Cannot read properties of undefined (reading 'last')
    at module.exports.lastGeneratedTicketNumber (/Users/Shail/ticket-queues/src/services/TicketControl/TicketControl.service.js:55:30)
    at async module.exports.onCurrentTicketEmitter (/Users/Shail/ticket-queues/src/sockets/emitters/onCurrentTicket.emitter.js:6:16)
Client disconnected
Client connected from  ::1
MongooseError: Operation `ticketcontrols.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/Shail/ticket-queues/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:197:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
MongooseError: Operation `ticketcontrols.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/Shail/ticket-queues/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:197:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
TypeError: Cannot read properties of undefined (reading 'last')
    at module.exports.lastGeneratedTicketNumber (/Users/Shail/ticket-queues/src/services/TicketControl/TicketControl.service.js:55:30)
    at async module.exports.onCurrentTicketEmitter (/Users/Shail/ticket-queues/src/sockets/emitters/onCurrentTicket.emitter.js:6:16)`
```

**Comment by AntennaeVY** [comment]
It says connection refused to the MongoDB database, where is your MongoDB Instance running? You set it up to be localhost:27017 but it seems there's no instance running there
